/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bbcvplayercore_libcore_LibCore */

#ifndef _Included_org_bbcvplayercore_libcore_LibCore
#define _Included_org_bbcvplayercore_libcore_LibCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bbcvplayercore_libcore_LibCore
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_bbcvplayercore_libcore_LibCore_version
  (JNIEnv *, jobject);

/*
 * Class:     org_bbcvplayercore_libcore_LibCore
 * Method:    nativeNew
 * Signature: (Ljava/util/ArrayList;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_bbcvplayercore_libcore_LibCore_nativeNew
  (JNIEnv *, jobject);
 // (JNIEnv *, jobject, jobject);

/*
 * Class:     org_bbcvplayercore_libcore_LibCore
 * Method:    startPlay
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_bbcvplayercore_libcore_LibCore_startPlay
  (JNIEnv *, jobject);

/*
 * Class:     org_bbcvplayercore_libcore_LibCore
 * Method:    stopPlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_bbcvplayercore_libcore_LibCore_stopPlay
  (JNIEnv *, jobject);

/*
 * Class:     org_bbcvplayercore_libcore_LibCore
 * Method:    pausePlay
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_bbcvplayercore_libcore_LibCore_pausePlay
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
