/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yyd_org_testJni */

#ifndef _Included_yyd_org_testJni
#define _Included_yyd_org_testJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yyd_org_testJni
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_yyd_org_testJni_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
