/* DO NOT EDIT THIS FILE - it is machine generated */
#include "testhJni.h"
//#include <string>
/* Header for class yyd_org_testJni */

/*
 * Class:     yyd_org_testJni
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_yyd_org_testJni_hello
  (JNIEnv *env, jobject thisz)
{


	return (*env)->NewStringUTF(env,"hello in yyd org orgtestjni");

}
